services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379" # Redis/FalkorDB port
      - "3000:3000"  # FalkorDB Browser interface
    volumes:
      - falkordb_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false # Makes the file optional. Default value is 'true'
    depends_on:
      falkordb:
        condition: service_healthy
    environment:
      - FALKORDB_HOST=${FALKORDB_HOST:-falkordb}
      - FALKORDB_PORT=${FALKORDB_PORT:-6379}
      - FALKORDB_USERNAME=${FALKORDB_USERNAME}
      - FALKORDB_PASSWORD=${FALKORDB_PASSWORD}
      - FALKORDB_DATABASE=${FALKORDB_DATABASE:-default}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PATH=/root/.local/bin:${PATH}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-10}
    ports:
      - "8001:8001" # Expose the MCP server via HTTP for SSE transport
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

volumes:
  falkordb_data:
